### ISSUE TITLE
GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT crash on multiplayer client

### ISSUE THREAD

**Issue by Mirsario** [Minenash/Seamless-Loading-Screen#1]
A friend of mine had the following crash when disconnecting from a server:
[crash-2020-12-21_22.28.33-client.txt](https://github.com/Minenash/Seamless-Loading-Screen/files/5726258/crash-2020-12-21_22.28.33-client.txt)

It should be noted that we use optifabric + optifine, though the mod doesn't conflict with it in its main function.

**Comment by Minenash** [comment]
Is it an everytime thing, or only sometimes?

**Comment by Mirsario** [comment]
Seems to happen every time.

**Comment by Minenash** [comment]
Also what minecraft version are y'all using?

**Comment by Mirsario** [comment]
![image](https://user-images.githubusercontent.com/6795251/102818631-1726fb80-43e3-11eb-85e1-3e124dfcf0b7.png)
The log has that as well as all the mods. I can send you them in discord in case of you not being able to reproduce it.

**Comment by Minenash** [comment]
(Don't know how I missed that tbh) At the current moment, I can't reproduce it, because I can't load into a server world without crashing. Though I'm doing it in a dev environment, so I'ma try in a normal install

**Comment by Minenash** [comment]
Okay in a normal install, it didn't crash on server load, but it also didn't crash on disconnect. So the zip of mods you offered would be useful

**Comment by Dragon-Seeker** [comment]
Due to the age of this issue and the rewrite that took place, I am closing this issue. If the issue returns please make a new issue.
