### ISSUE TITLE
[Enhancement] Config to Save Screenshot to Screenshots folder

### ISSUE THREAD

**Issue by milkev** [Minenash/Seamless-Loading-Screen#10]
It would be awesome if you could have a config option to save each of the screenshots taken to the \screenshots folder as well.

Some people like taking a lot of screenshots for memory/whatever purposes, and this could help towards that end. Or if you just want to save them because you can, theres a lot of reasons one might want them all saved.

I know you are able to copy/paste the screenshot from the custom folder, I was hoping for something automatic.

**Comment by Minenash** [comment]
Yeah, I can add it. it'll still be a subfolder, but the mod will just copy the file to the archive folder every time it takes it

**Comment by Minenash** [comment]
Added in v1.2.1
