### ISSUE TITLE
1.21 Support

### ISSUE THREAD

**Issue by Pie-Not-Lie** [Minenash/Seamless-Loading-Screen#110]
Mod needs to be updated to work with 1.21 :)

**Comment by N1zyx3** [comment]
Yes, I really want to see him at 1.21

**Comment by Scubakay** [comment]
Sooo, no development on this mod anymore?

**Comment by N1zyx3** [comment]
> Ну что, эта мода больше не разрабатывается?

Why? Perhaps the developer has encountered problems and cannot update the mod right now

**Comment by Dragon-Seeker** [comment]
Currently, other projects and mods are being dealt with at the moment. Seamless is planned to be updated but such may be some about of time. I have yet to look at the changes nor look at the bugs to attempt fixes so please be patient.

**Comment by Dragon-Seeker** [comment]
Such has been done, uploaded to both modrinth and curseforge
