### ISSUE TITLE
[Request] set world thumbnail option

### ISSUE THREAD

**Issue by supersaiyansubtlety** [Minenash/Seamless-Loading-Screen#13]
It would be nice if the world thumbnail could also set to the exit screenshot every time, so you can remember exactly where you were when you quit/logged out before starting to load/login.

**Comment by Minenash** [comment]
As soon as I can find where minecraft does this, so I can trigger it, I will

**Comment by Minenash** [comment]
Added in v1.3.0 and v1.3.1

**Comment by supersaiyansubtlety** [comment]
thanks!
