### ISSUE TITLE
Incompatibility with Fabric API 0.30.0

### ISSUE THREAD

**Issue by Toseflo** [Minenash/Seamless-Loading-Screen#15]
When you use Seamless Loading Screen with Fabric API 0.30.0 in Minecraft 1.16.5 and exit a world, the game crashes every time. Crash Report ist attached
[crash-2021-01-28_13.34.12-client.txt](https://github.com/Minenash/Seamless-Loading-Screen/files/5887123/crash-2021-01-28_13.34.12-client.txt)

**Comment by Minenash** [comment]
After testing a bit, I've made an issue in the fapi repo about it

**Comment by truesilver92** [comment]
I can confirm that I had crashing on save & exit with Fabric API 0.30.0+1.16 in Minecraft 1.16.5. Downgrading to Fabric API 0.29.4+1.16 fixed the problem

**Comment by Minenash** [comment]
Temporary fix added in v1.2.0 and v.1.2.1. A less terrible fix should be added in v1.2.2

**Comment by Minenash** [comment]
Correction. Fix was added in v1.2.0, accidentally unfunctional in v1.2.1, but functional again in v1.2.2
