### ISSUE TITLE
[Request]Ability to add blur to screenshots.

### ISSUE THREAD

**Issue by Dbl7id** [Minenash/Seamless-Loading-Screen#16]
It'd awesome if we could add blur to the screenshots taken along with being able to adjust how much blur is applied.

Although this is mainly just my preference, the screenshots look uncanny to me when paired with the loading square.

**Comment by Minenash** [comment]
I might add it in the future, but for now, you can always use the Blue mod for fabric. It also applies to all the screens, though.

**Comment by RDKRACZ** [comment]
+1 to this, I would use the blur mod but it lags the game every time when I open my inventory.

**Comment by RDKRACZ** [comment]
Also, the text "loading world" etc. would be more readable.

**Comment by spikespaz** [comment]
The Blur mod is the current best solution here. I don't think this is going to be a priority any time soon. I won't call it quite "out of scope" but it is a bit more involved than I would like.

**Comment by Minenash** [comment]
Will be in the next release ([commit](https://github.com/Minenash/Seamless-Loading-Screen/commit/b5cba59f4db034e4d03d860502937e8e68b8a599))
