### ISSUE TITLE
Leaving world shrinks screen on macOS

### ISSUE THREAD

**Issue by magicus** [Minenash/Seamless-Loading-Screen#21]
First of all, thanks for a fantastic idea! This should really have been the default in Minecraft.

Unfortunately, I can't use this. On my Mac, when I load this mod, I get to a weird state where the game still behaves as if it is full screen, but only the lowest left 1/4 is painted. I'm guessing this might be some Retina display issue. 

FWIW, I had the same problem for earlier Minecraft releases with Forge, unless I disabled the Forge loading screen. (This I just resolved by going from Forge to Fabric :))

**Comment by magicus** [comment]
I realize this bug report is pretty light on details. Let me know what additional information you might require, and I'll provide it.

**Comment by magicus** [comment]
Screen cap:
https://user-images.githubusercontent.com/6209108/107392852-642d7100-6afa-11eb-8e83-bb77ed9159e1.mp4

**Comment by magicus** [comment]
My initial description was wrong -- this problem manifest itself both with and without full screen, so that was a red herring. In the video, you can see that when I save and exit a world, the Minecraft main screen only occupy 1/4 of the window  from that point on. By going to fullscreen, and back again, the normal screen is restored.

**Comment by Minenash** [comment]
If it's caused by leaving, does it still happen if you change the resolution setting to Native?

**Comment by magicus** [comment]
Yay, that worked!

**Comment by magicus** [comment]
While the immediate problem is solved for me, it would be nice if this did not happen. Maybe "Native" should be default? Or be default on Macs, or on Macs with Retina displays..? (Which I'm assuming has something to do with this)

**Comment by Minenash** [comment]
I can try out the theory with the display, but it's definitely not mac wide, as someone was using this on a mac without this type of problem.

The reason it's not default, is because it's the worst option. If the window's aspect ratio is wider than it was when exiting the world, then you see bars on both sides, and the fade is weird. It was added as a compatibility mode for some optifine shaders, as the ultra quick resize then screenshot caused blurred images.

**Comment by Minenash** [comment]
Can you try this special build and see if the bug persists? (just take the jar out of the zip, github won't let me post jars directly)
[seamless-loading-screen-1.3.0.zip](https://github.com/Minenash/Seamless-Loading-Screen/files/5952863/seamless-loading-screen-1.3.0.zip)

**Comment by magicus** [comment]
Unfortunately no difference. :( "Normal" mode is buggy just the same, and "Native" works. At this point, I'm happy with using native. If you want to pursue finding the core issue, I'll help you as best as I can, but I can also understand if you just want to close this bug (and maybe add a note in the readme).

**Comment by Minenash** [comment]
Yeah, I think I'll have too, the change in there was the only thing I could think of that would change the behavior (the change will stay because it also simplifies the code a small bit). Bassically changing the resolution at all causes your mc to bug out

**Comment by Minenash** [comment]
I think I remember hearing something about MC on macOS running at half the resolution to help improve performance. Either way, the mod now reverts to whatever the buffer size was right before the change, thanks to #32. The latest release (v1.3.4) includes this fix.

**Comment by magicus** [comment]
This does indeed seem to work properly! Thanks for the fix!
