### ISSUE TITLE
Game crashes when disconnecting from any server

### ISSUE THREAD

**Issue by blackcat-917** [Minenash/Seamless-Loading-Screen#23]
Hi, when I disconnect from a server (I tried with [Hypixel ](hypixel.net) and [Mineplex](mineplex.com)) the game crashes showing me a `Not enough crashes` screen.
The mod took the screenshot because on rejoin it's displayed.
Also, when I rejoin the server, the GUI is in F1-mode then not displayed.

The crash log is here: <https://pastebin.com/gAgPvvQx>

Here is the crash screen:

![image](https://user-images.githubusercontent.com/53786619/107532521-46294480-6bbe-11eb-8d09-5ebaad69f798.png)

**Comment by Minenash** [comment]
Thanks for the report! I'm about to look to see what causes the error, but I do know the gui being hidden use because it crashes before it can re-enable it

**Comment by Minenash** [comment]
I am an idiot, I didn't check if the player was on singleplayer or multiplayer before attempting to update the world icon. Until the fix is released, turn off "Update World Icon"

**Comment by Minenash** [comment]
v1.3.1 has been released
