### ISSUE TITLE
[Request] Screenshot when you get kicked

### ISSUE THREAD

**Issue by Toseflo** [Minenash/Seamless-Loading-Screen#24]
When you get kicked from the server or lose connection, it doesn't take a screenshot currently. Would be nice if this could be added.

**Comment by Minenash** [comment]
didn't even think of that, totally will add

**Comment by Toseflo** [comment]
Nice. I almost didn't notice it at first; I lost connection and then I was like "Wait this screenshot isn't right" xD

**Comment by Minenash** [comment]
Fixed in v1.3.3
