### ISSUE TITLE
[Bug] Crash when there is illegal character in realm server name 

### ISSUE THREAD

**Issue by HackerPide** [Minenash/Seamless-Loading-Screen#27]
Happens when i try to use the mod by leaving this realms server: "Flawless clan! <3"
[crash-2021-03-10_10.56.19-client.txt](https://github.com/Minenash/Seamless-Loading-Screen/files/6114706/crash-2021-03-10_10.56.19-client.txt)
`java.nio.file.InvalidPathException: Illegal char <<> at index 41: screenshots\worlds\realms\Flawless clan! <3.png`
The problem for this instance is the '<' character.

**Comment by Minenash** [comment]
Hmm, so I could either run the name through the same method that minecraft uses for world names to be file-safe, or I would switch to using the realm id. I think I'll go for the former. While the latter would basically end any chance of file name issues for realms, it would also make them hard to find for a user wanting to copy the file

**Comment by Minenash** [comment]
Fixed in v1.3.3
