### ISSUE TITLE
Incompatibility with HUDTweaks

### ISSUE THREAD

**Issue by CodeF53** [Minenash/Seamless-Loading-Screen#31]
I am not quite what mod this falls on, but here is the issue:

After repositioning StatusEffects to be next to my hotbar, Seamless loading screen now displays my status effects as of logging out in a really odd location:
![image](https://user-images.githubusercontent.com/37855219/113068513-a7f83a80-917b-11eb-845c-61cf2ecf25c8.png)

**Comment by Minenash** [comment]
It's not a particular mods "fault". This mod uses `options.hudHidden` to disable hud stuff. All pressing F1 is, is setting that boolean. However some stuff still renders when F1 is on, but a screen is open (seamless loading screen opens an empty screen to make sure the screenshot is taken at the right time).

To fix this, ask them to check options.hudHidden before rendering

**Comment by burgerguy** [comment]
I'm pretty sure some elements of the HUD, including status effects, don't check for `options.hudHidden` in vanilla when it's already inside `InGameHud.render()`. However, that function only gets called (in `GameRenderer`) if it passes `!this.client.options.hudHidden || this.client.currentScreen != null`. I think maybe this mod is doing something with the screen to where it passes the check before it usually should be able to. I haven't done any testing though, so take this with a grain of salt.

**Comment by burgerguy** [comment]
I'm pretty sure this bug happens in vanilla as well, but I haven't tested it. HUDTweaks doesn't render anything extra, so this is being called because `InGameHud.render()` is being called. Maybe mixin to `InGameHud.render()` and cancel the method when it's loading like this.

**Comment by DaDerpDuck** [comment]
I don't know much about Fabric, but Forge's equivalent of this is to cancel the RenderGameOverlayEvent, which is hooked from another class called IngameGui (hmmmmm..)
The render call is made when hudHidden is disabled OR if there's a screen being displayed (I guess this is so that when you're in F1 mode, chat wouldn't be invisible when you're typing)
Canceling the render call will also fix the debug menu (#28) from displaying, along with chat, boss healthbars, InventoryHUD, and this issue too :D

**Comment by Brittank88** [comment]
Just want to say that I am having this issue with both InventoryHUD+ and Advanced Compass, and they _do_ hide when I press F1.

**Comment by Dragon-Seeker** [comment]
Should not be an issue going forward thanks to the rewrite of the mod on how and when it takes screenshots
