### ISSUE TITLE
"[main/INFO]: [STDOUT]: TEST" spam in console when installed alongside Optifabric/Optifine

### ISSUE THREAD

**Issue by mheps** [Minenash/Seamless-Loading-Screen#33]
Modlist:
![image](https://user-images.githubusercontent.com/29741016/115329177-ea4fde80-a15f-11eb-9d6a-9db098c91fac.png)

[STDOUT]: TEST is entered into console about once a second while Seamless Loading Screen is installed alongside Optifabric and Optifine.

![image](https://user-images.githubusercontent.com/29741016/115329366-3438c480-a160-11eb-9c87-b996c1a46215.png)

https://pastebin.com/GtTRvB6G

**Comment by Minenash** [comment]
Fixed in latest release (v1.3.4)
