### ISSUE TITLE
Bad performance

### ISSUE THREAD

**Issue by Delivator** [Minenash/Seamless-Loading-Screen#35]
This mod adds a significant delay when disconnecting from a server.
With the mod installed disconnecting from a server takes 1.3 seconds on my PC.
Without the mod it's literally instant, not even one frame on a 60fps recording.
A normal ingame screenshot (F2) is also instant.
On singleplayer the delay is not really noticeable, since the world needs to save too.
I hope this can be improved.

**Comment by Minenash** [comment]
Does the performance impact lessen if you switch the resolution option to native?

This is the quit routeing:
if resolution option is not set to native: Change resolution (the default option makes sure there is never side bars when loading at a different aspect ratio)
Turn off the HUD
Open a blank screen (This allows us to take the screenshot during the first render where the HUD is off)
Take screenshot using mc's util
if resolution option is not set to native: Change resolution back

**Comment by Delivator** [comment]
Switching to native resolution doesn't seem to make a difference on the delay.

**Comment by Dragon-Seeker** [comment]
Due to the performance impact being 1.3 seconds, I really doubt that such is a problem tbh.
