### ISSUE TITLE
Incompatibility with latest Sodium commit

### ISSUE THREAD

**Issue by OsoaGH** [Minenash/Seamless-Loading-Screen#36]
Here is the commit I'm using: [Link](https://github.com/CaffeineMC/sodium-fabric/commit/9fbf07a2f88476ce4663cef73060c2c43267b05b) although it could be an earlier commit.

**Comment by Minenash** [comment]
Fixed on local, will make a new release when I fixed the few other recent issues

**Comment by OsoaGitHub** [comment]
will this update includea version 1.16.5?

**Comment by spikespaz** [comment]
Closing because it's stale and shouldn't be a problem anymore as far as I can tell.
