### ISSUE TITLE
[1.17 only] Suspected Mod Conflict with Seamless Loading Screen and Screenshot to clipboard: Crash when trying to disconnect from server

### ISSUE THREAD

**Issue by Blobanium** [Minenash/Seamless-Loading-Screen#40]
so when i try to disconnect from the server, the game seems to crash. And looking at the crash log seems to be a Conflict with Screenshot to clipboard and Seamless loading screen.

anyways heres the crash log
[crash-2021-06-25_13.54.04-client.txt](https://github.com/Minenash/Seamless-Loading-Screen/files/6718813/crash-2021-06-25_13.54.04-client.txt)

if theres anything else that u need tell me.

**Comment by Minenash** [comment]
Does taking a normal screenshot work?

**Comment by Blobanium** [comment]
> Does taking a normal screenshot work?

it seems to do the same thing yes

**Comment by Minenash** [comment]
Do you mean it does it doesn't crash when you do F2?

**Comment by Blobanium** [comment]
it seems to crash if you take a screenshot so yes it does crash if you do F2.

**Comment by Minenash** [comment]
And I'm assuming you removed seamless loading screen and it worked again?

**Comment by Blobanium** [comment]
> And I'm assuming you removed seamless loading screen and it worked again?

yes it works again and doesnt crash if you try to leave a server or take a screenshot

**Comment by Dragon-Seeker** [comment]
Such has been fixed on the latest version of the mod. It dose require you update to later versions to have such fixed.
