### ISSUE TITLE
Crash when disconnecting from server (1.17)

### ISSUE THREAD

**Issue by cpm9** [Minenash/Seamless-Loading-Screen#41]
Fabric loader 0.7.4

Mods present:

- Fabric api 0.36.0
- Mod menu 2.0.2
- Not Enough Crashes 3.3.1
- Optifabric 1.11.6
- Optifine G9 pre24
- Screenshot to clipboard 1.0.6
- Seamless loading screen 1.3.5

[crash-2021-06-28_23.30.58-client.txt](https://github.com/Minenash/Seamless-Loading-Screen/files/6730894/crash-2021-06-28_23.30.58-client.txt)

**Comment by Minenash** [comment]
Dublicate of #40
