### ISSUE TITLE
[Request] Takes screenshot with blur when Blur is installed

### ISSUE THREAD

**Issue by piemanau** [Minenash/Seamless-Loading-Screen#42]
When I have the mod blur installed it takes a screenshot with the blur from it, could we get a config option for it so we get a choice for if it uses the blur or not? Thank you for considering/trying!

**Comment by 31j** [comment]
I'd have to check, but doesn't blur have an exclusion parameter? I.e you can exclude the blur from specific guis

**Comment by Minenash** [comment]
If that's true, then it'll be easy to add the config

**Comment by 31j** [comment]
![Screenshot 2021-06-29 144620](https://user-images.githubusercontent.com/32624322/123851205-ec18e980-d8e8-11eb-9683-9ca2ab95e7ff.png)
![Screenshot 2021-06-29 144615](https://user-images.githubusercontent.com/32624322/123851211-ed4a1680-d8e8-11eb-85f0-eabc7d1249b4.png)

**Comment by 31j** [comment]
the blur exclusions part is where it'd go, as of now you sadly can't edit them in game but you can manually edit them from the .json

what i've sent is the default, I'm fairly certain that's the chat window being excluded

**Comment by 31j** [comment]
Would the "Game Menu" have to be excluded, i.e is Seamless loading screen taking the screenshot in this menu (when you press save and quit)

or is there a specific exclusion that would work without impacting blur's functionality?

**Comment by Minenash** [comment]
The exclusion would be `com.minenash.seamless_loading_screen.FinishQuit`.

**Comment by LimeShulkerBox** [comment]
Oh cool are you going to implement it or do you not think it is worth it

**Comment by 31j** [comment]
## The exclusion works
### Example of loading screen without blur (ignore the inventory hud issue)
![Screenshot 2021-06-29 170347](https://user-images.githubusercontent.com/32624322/123867201-0b6d4200-d8fc-11eb-9ef6-6590c62b9d58.png)
### blur.json (located in /config/blur.json). 
#### Remember to use a comma at the end of all items except the last one
![Screenshot 2021-06-29 170409](https://user-images.githubusercontent.com/32624322/123867204-0c05d880-d8fc-11eb-903f-715895444a78.png)

> Oh cool are you going to implement it or do you not think it is worth it

Not entirely sure what can be done on the implementation of Seamless Loading Screen as the solution is to add an entry into the config of a different mod.

**Comment by 31j** [comment]
## Instructions for people who find this issue and have blur / seamless loading screen.

0. Launch minecraft once with both mods installed to create the config files
1.  Go to your minecraft folder, specifically the config
      - ~/Library/Application Support/minecraft/config [macOS]
      - ~/.minecraft/config [Linux]
      -  %AppData%\\.minecraft\config [Windows]
      - MultiMC: Edit instance -> Loader mods -> View Configs
2. Edit blur.json with the editor of your choice 
3. Add `com.minenash.seamless_loading_screen.FinishQuit` to the exclusions list. Add a comma to the end of the previous entry [See image in previous comment]
4. Profit

**Comment by LimeShulkerBox** [comment]
The problem is that I want it on that screen lol,  is there anyway to get around this with it still being there?

**Comment by Minenash** [comment]
You don't see the FinishQuit screen though, it closes itself in it's first render call

**Comment by luni3359** [comment]
@31j how did you fix the inventory hud problem?

**Comment by Minenash** [comment]
The next update will have the ability to blur screenshots ([commit](https://github.com/Minenash/Seamless-Loading-Screen/commit/b5cba59f4db034e4d03d860502937e8e68b8a599))
