### ISSUE TITLE
Missing Fade Effect (you can also move during the loading screen but idk if that's intended)

### ISSUE THREAD

**Issue by TAKfsg** [Minenash/Seamless-Loading-Screen#43]
I don't know if it's my problem but the latest version on curseforge for 1.17 misses the fade-in effect. Using fabric-api 0.36.0 btw.

Edit: you can also move during the loading screen but idk if that's intended

**Comment by Dragon-Seeker** [comment]
Fixed with the latest rewrite of the mod
