### ISSUE TITLE
Game crashes using the cursor mod

### ISSUE THREAD

**Issue by Varshious** [Minenash/Seamless-Loading-Screen#44]
The game crashes when leaving a world using this mod and the cursor mod
This is the crash report https://gist.githubusercontent.com/natanfudge/e683226d0d2723044afaa357812b8d4a/raw/e40542d73e4d785f339a618dd05cbebfe3748594/crash.txt
I don't know anything about modding or this issue I just hope it can be resolved

**Comment by Minenash** [comment]
When does this crash occur?

**Comment by Varshious** [comment]
> When does this crash occur?

Every time I leave the world

**Comment by Minenash** [comment]
Hmm, I could have to look into it, ~~I did a quick look at their code, and it would be weird ~~ Hmm, I think I know the problem, they use fabric's after render event, which does have problems with my mod, normally this would be fine, but it looks like his thing doesn't consider the screen being null (which is fair actually, neither does fabric). Probably the best solution would be me doing a mixin to do a null check. But I would need to look at his code again to make sure my theory is correct

**Comment by Dragon-Seeker** [comment]
Rewrite should fix this issue at hand
