### ISSUE TITLE
[1.17.1] Client crashes on launch

### ISSUE THREAD

**Issue by snessim** [Minenash/Seamless-Loading-Screen#45]
**_Client crashes during startup when Seamless Loading Screen is present._**
Version: 1.17.1 / fabric 0.11.6
Mods: FabricAPI 0.36.1+1.17 RC-2, Seamless Loading Screen 1.3.5+1.17
Full crash log: https://paste.ee/p/et6mr
dxdiag dump: https://paste.ee/p/9cqAR

Extra testing:
1.17.0 with Fabric 0.11.6 + SLS 1.3.5 + FAPI 0.36.0 **does not crash**
1.17.1 with Fabric 0.11.6 + SLS 1.3.5 + FAPI 0.36.1 latest dev build at time of report (#2445) **crashes**

**Comment by Minenash** [comment]
Just to make sure, this doesn't happen in 1.17 right?

**Comment by snessim** [comment]
> Just to make sure, this doesn't happen in 1.17 right?

Correct, that is what I was double checking under "extra testing". There is no issue in 1.17.0, though I can only check that with FAPI 0.36.0 so I can't confirm if it's a change in the API causing the conflict.

**Comment by Minenash** [comment]
Oh, sorry, I had only noticed the api version change

**Comment by SpiffyJUNIOR** [comment]
same issue here. 1.17.1 with latest fabric api and latest fabric version

**Comment by Minenash** [comment]
Didn't mean to close it.

I'm sorry I haven't gotten around to looking into this, I've been pretty busy lately. I should have time by this weekend though

**Comment by leftl** [comment]
Artifacts from #46 resolved this crash for me, just a heads up to others!

**Comment by rarescolibaba** [comment]
@Minenash Could you create a release here and on Modrinth which includes #46? It fixed crashes for me too.

**Comment by Minenash** [comment]
I'll do it first think in the morning

**Comment by Minenash** [comment]
Released
https://modrinth.com/mod/seamless-loading-screen/version/JWUaioGR
https://www.curseforge.com/minecraft/mc-mods/seamless-loading-screen/files/3403066
https://github.com/Minenash/Seamless-Loading-Screen/releases/tag/v1.3.6%2B1.17.1
