### ISSUE TITLE
Very Broken Screenshots + Suggestions

### ISSUE THREAD

**Issue by MadDog443** [Minenash/Seamless-Loading-Screen#50]
- Majority of the time screenshots will not be updated, almost 100% of the time it will be stuck on a incorrect screenshot which it will use for all other servers you connect to.

- Also for servers where you are forced to connect to a HUB server this does not work due to the fact that you leave from a different location than where you always join, a solution would be to have a setting when adding a server to your list that allows you to take a permanent screenshot for where you connect in the hub, also perhaps figure out a way to detect when changing worlds and tie the screenshots to those to solve the issue of always connecting via a hub world

- What if you loosely tie it to coords so you get seamless loading screens when you go through nether portals or end portals.

- Although the best solution could be a server-side plugin/mod that allows the server to supply the images for things like portals, etc.

**Comment by MadDog443** [comment]
Here's my modpack I'm using rn, it's a WIP but it has logs too.
https://www.mediafire.com/file/czx2zaan4fq4yeq/MadPack+1.17.1.7z/file

**Comment by MadDog443** [comment]
@Minenash Any luck?

**Comment by Dragon-Seeker** [comment]
Due to the rewrite of the mod and the age of the issue, I am closing this issue but will be noting the requests as a separate issue. If this reoccurs with the latest version please open a new issue
