### ISSUE TITLE
cm-360's 1.18.1 port woks perfectly but it has a small incompatibility issue with ASH(another simple hud)

### ISSUE THREAD

**Issue by EGOIST1372** [Minenash/Seamless-Loading-Screen#56]
cm-360's 1.18.1 port works perfectly but it has a small incompatibility issue with [ASH(another simple hud)](https://www.curseforge.com/minecraft/mc-mods/ash-another-simple-hud)
screenshots are attached
screenshot#1: normal ASH look
![2022-02-10_17 52 27](https://user-images.githubusercontent.com/86555131/153434403-1571c1f1-744f-4e96-8a66-2f9e7c6af3b2.png)
screenshot#2: in loading screen, ASH is a bit present on screenshot that taken before logging out by SLS in top left corner
![2022-02-10_18 16 40](https://user-images.githubusercontent.com/86555131/153434565-e038c14f-82a4-49df-9777-3da535f0b25c.png)

**Comment by EGOIST1372** [comment]
also don't mind the difference between screenshot. in one i had night vision. screenshots are just for demonstration

**Comment by Dragon-Seeker** [comment]
Should not be an issue with the latest rewrite with how and when screenshots are taken
