### ISSUE TITLE
Add option to disable mod on servers

### ISSUE THREAD

**Issue by Pectacular** [Minenash/Seamless-Loading-Screen#59]
Many servers have a 'Hub' or 'Lobby' to which the player is taken to every time they join the server. Because of this, every time I leave a server, the place where the screenshot was taken is not where I will be when I rejoin the server.

**Comment by spikespaz** [comment]
How do you think this should be implemented?
Should we have an option on the "Edit server" screen that has a checkbox for this, or are you simply asking for a configuration file with a list of server names to disable this for?

**Comment by Minenash** [comment]
This already can be done, though maybe better worded. If you go into the server settings, there should be an option called "Custom Screenshot". When this is turned on, it doesn't take a screenshot on closing. The original intention was for you to take a screenshot of the hub itself, but you can also turn on the option and just delete the screenshot already existing (if there's one), which in effect disabled it

**Comment by spikespaz** [comment]
Given that, I can also add a disable button to be straightforward.

**Comment by Minenash** [comment]
That'd be good, another possibility could be a button that cycles between 3 options:
- On/Enabled
- Frozen/Custom
- Disabled

**Comment by Pectacular** [comment]
> That'd be good, another possibility could be a button that cycles between 3 options:
> 
>     * On/Enabled
> 
>     * Frozen/Custom
> 
>     * Disabled

Having a button that cycles between these three options would definitely be the best option.

**Comment by Minenash** [comment]
Will be in the next release ([commit](https://github.com/Minenash/Seamless-Loading-Screen/commit/4886368b79bd822ac951e8c91eda65d178298f71))
