### ISSUE TITLE
Different image when leaving world in third person

### ISSUE THREAD

**Issue by luni3359** [Minenash/Seamless-Loading-Screen#60]
When you leave the world in third person the mod takes a screenshot in third person but when you join you always enter in first person so the transition is a bit confusing.

**Comment by spikespaz** [comment]
@Minenash Do you think it would be feasible to change the player to first-person before taking the screenshot, or implement a custom camera thingy to avoid some of the other issues in the same go?

**Comment by Minenash** [comment]
Idk about the custom camera thing, but changing to first person could be done really quickly, by running wherever method F5 runs before the screenshot is taken. Should be only be one line of code.

And you can then remove it when/If you implement a custom camera thing

**Comment by Minenash** [comment]
Will be fixed in the next release ([commit](https://github.com/Minenash/Seamless-Loading-Screen/commit/753e237095bb3e6fe3458d1a7d1dd019df533ba6))
