### ISSUE TITLE
Player stays in the server on quit (进入服务器一段时间后退出服务器时退不利索)

### ISSUE THREAD

**Issue by wearfa** [Minenash/Seamless-Loading-Screen#64]
退不利索的意思是每次我退出游戏会黑屏一小段时间之后就到标题界面 ，但是游戏人物还在服务器内，重新加入服务器会显示你已经在服务器内了 这个问题一直有 1.18-1.19其他版本我没试 希望解决

**Comment by Minenash** [comment]
可能是 #47 的副本

这对我来说不再是一个活跃的项目（你可能可以从未解决的问题的数量中看出），所以我不能说这会很快得到解决，但如果我回到这个 mod 的工作上，这肯定会 优先

**English (英语):**
Probably a dublicate of #47

This is no longer an active project for me (as you can probably tell by the amount of open issues), so I can't say this will be fixed soon, but if I ever get back to working on this mod, this will definitely be high priority

**Comment by Dragon-Seeker** [comment]
Duplicate of #47
