### ISSUE TITLE
Incompatible with Quilt Loader

### ISSUE THREAD

**Issue by ioococ** [Minenash/Seamless-Loading-Screen#75]
Generally for any future issues or people looking over this with an issue on quilt:

Seamless Loading Screen is a fabric-first mod and although it should work completely fine on quilt we cant guarantee it.

<details><summary>Original Issue</summary>
<p>

![image](https://github.com/Minenash/Seamless-Loading-Screen/assets/51018049/71c4e43c-d9b3-4958-a84f-7e2260784826)

[crash-2023-08-19_18.23.55.7660-quilt_loader.txt](https://github.com/Minenash/Seamless-Loading-Screen/files/12385574/crash-2023-08-19_18.23.55.7660-quilt_loader.txt)

I have to manually modify the fabric.mod.json to start the game

</p>
</details>

**Comment by Minenash** [comment]
Are you using the latest version of the loader?

**Comment by Minenash** [comment]
Next release will be more lenient on the loader requirement. It doesn't need to be this high

**Comment by IMB11** [comment]
Yeah, we'll set it to `*`.

Generally for any future issues or people looking over this with an issue on quilt:

Seamless Loading Screen is a fabric-first mod and although it should work completely fine on quilt we cant guarantee it.

**Comment by ioococ** [comment]
> Are you using the latest version of the loader?

yes

**Comment by Dragon-Seeker** [comment]
Could you try the latest release to confirm if this is still an issue: https://modrinth.com/mod/seamless-loading-screen/versions

**Comment by ioococ** [comment]
oh thanks
