### ISSUE TITLE
[Bug] Incompatibility with FastQuit: Cannot move mouse upon world loading

### ISSUE THREAD

**Issue by 10kmotorola** [Minenash/Seamless-Loading-Screen#76]
Can't move or click anything.

[Log](https://pastebin.com/7gXeanWH)

**Comment by TinsleyDevers** [comment]
Having the same issue! [Fabric] Seamless Loading Screen 2.0.0+1.20.1

**Comment by 10kmotorola** [comment]
Oops didn't realized PasteBin would expire my link. Here's a text file:

[log.txt](https://github.com/Minenash/Seamless-Loading-Screen/files/12444464/log.txt)

**Comment by Dragon-Seeker** [comment]
The issue seems to be with the FastQuit mod that leads to this issue, Ill need to investigate further a solution to fix it.

**Comment by 10kmotorola** [comment]
The bug still persists even after disabling FastQuit.

**Comment by Dragon-Seeker** [comment]
It would be great if you could fix what mod might be causing this as I did a test with fast quit and found some issues with such. It may take a bit to find what exactly is causing this.

**Comment by 10kmotorola** [comment]
Did some testing; the issue seems to be with [kennytvs-epic-force-close-loading-screen-mod-for-fabric](https://modrinth.com/mod/forcecloseworldloadingscreen?hl=en-US). Makes sense considering what it does.

**Comment by Dragon-Seeker** [comment]
Add a fail-safe for this issue and change the priority of mixin to hopefully have better compatibility.

**Comment by Dragon-Seeker** [comment]
Could you try the latest release to confirm if this is still a issue: https://modrinth.com/mod/seamless-loading-screen/versions

**Comment by 10kmotorola** [comment]
Works perfectly now :) thanks a ton!!

**Comment by Dragon-Seeker** [comment]
Cool, will be closing the issue as solved
