### ISSUE TITLE
 Incompatible with BcLib

### ISSUE THREAD

**Issue by MbtMarco** [Minenash/Seamless-Loading-Screen#80]
Bclib is the library for Better End/Nether.
When you join a server you have to synchronize the BcLib configuration files with the server configuration files however because of Seamleass Loading Screen I can't move the mouse cursor to select a screen option.

**Comment by Thebigboss537** [comment]
I have the same error

**Comment by Dragon-Seeker** [comment]
A log, Video and a list of mods would be great to better diagnose the issue at hand.

**Comment by MbtMarco** [comment]
At the moment I can't send you any of that, if you wait tomorrow I'll send you video, log and mod list.

**Comment by Dragon-Seeker** [comment]
Also may be a good idea to confirm that the bug still exists with the latest update since I added a fail safe to prevent lockup like this.

**Comment by MbtMarco** [comment]
I don't encounter the bug anymore, I removed some mods like Mindfull Darkness, maybe those were the problem. Thanks for everything anyway.
