### ISSUE TITLE
Game Stuck at a screenshot + mixed up screenshot for worlds (2 issue in 1)

### ISSUE THREAD

**Issue by EGOIST1372** [Minenash/Seamless-Loading-Screen#81]
Hi
recently minecraft launcher added a feature that you can directly log into your server or single player world without needing to load minecraft and go through menus
and issue is that it stuck at a screenshot of the world it took and nothing loads. i hear minecraft menu sounds but its stuck at that screenshot

step to reproduce the issue:
1. install seamless loading screen 1.20.1
2. use it into your single player world
3. make sure it saved at least one screenshot as loading screen before proceed to next step
4. now exit minecraft
5. then go to minecraft launcher settings and turn on experimental feature
6. and then open minecraft again
7. then load your world again and then exit minecraft again
8. this time new quick launch option for your world will appear on top right hand side of minecraft launcher if not just relaunch the launcher
9. now quick start to your world (first time usually works fine) then exit minecraft again
10. relaunch launcher and start minecraft normally you do (dont use quick launch)
11. now it will stuck on the last screenshot mod took
![image](https://github.com/Minenash/Seamless-Loading-Screen/assets/86555131/dca0fabc-5f5c-49a8-8202-4b84dcc41d65)
![image](https://github.com/Minenash/Seamless-Loading-Screen/assets/86555131/4e90f9ec-f468-423a-9e2f-4b5b4239e8fc)

even after you disable the quick launch feature on minecraft it still stuck on screenshot (technically it stucks at main menu with a screenshot overlay that covering the whole screen :D ) it means that clicking on screen actually works if you know where are the buttons 

quick launch into world works in one condition if you do it into the last world you played (last screenshot saved for it) unless if you do it on another world it will say "failed to quick play , could not find world with the provided identifier"
![2023-08-29_21 17 55](https://github.com/Minenash/Seamless-Loading-Screen/assets/86555131/525b6963-bed2-4cba-a3f4-1ef9812f7483)

and even if you quick play into right world when you trying to exit the world, when you reach to main menu it again stuck at that screenshot unless you remember where is exit the game button on screen :D

also here rise another issue. make a single player world, enter it and exit it. now make another world and do the same, now when you load first world it shows second world's screenshot (it doesnt remember which screenshot is for which world and only remember the last screenshot it took)

**Comment by EGOIST1372** [comment]
to clarify, all issues will solve if you remove seamless loading screen mod

**Comment by EGOIST1372** [comment]
also idk if its relevant or not but I use fancy menu mod and i changed the main menu with it but i dont think it have anything to do with it since these 2 mods should not be related in any way and quick play works with that mod with no problem

**Comment by Dragon-Seeker** [comment]
Due to it being an experimental feature, not much time will be invested at the moment to track down the problem as other problems exist that are more pressing.

The bug dealing with incorrect screenshots applied to the wrong world dose not seem to happen with either dev or prod so I am not too sure how such happens.

**Comment by EGOIST1372** [comment]
since im not planning to use that experimental feature anymore is there anyway that i fix the issue that persists?
i deleted the seamless loading screen.json in config folder but still happens. is there a way to delete the cache of the mod?

maybe second issue related to mods like screenshot to clipboard or nicephore idk but i can record a video if you like to see it?!

**Comment by Dragon-Seeker** [comment]
A full list of mods and a video would be great to get a full understanding

**Comment by EGOIST1372** [comment]
also i found some warnings in launcher log

[Info: 2023-08-26 14:46:50.1018486: MinecraftJavaLoggingContext.cpp(52)] Game/FabricLoader/Mixin (main) Warn Reference map 'seamless-loading-screen-fabric-refmap.json' for seamless_loading_screen-fabric.mixins.json could not be read. If this is a development environment you can ignore this message

Info: 2023-08-26 14:46:50.1239879: MinecraftJavaLoggingContext.cpp(52)] Game/SodiumConfig (main) Warn Mod 'seamless_loading_screen' attempted to override option 'mixin.features.gui.fast_loading_screen', which doesn't exist, ignoring

[Info: 2023-08-26 14:47:20.7978506: MinecraftJavaLoggingContext.cpp(52)] Game/FabricLoader/Mixin (Render thread) Warn @Inject(@At("INVOKE")) Shift.BY=2 on seamless_loading_screen-common.mixins.json:GameRendererMixin from mod seamless_loading_screen::handler$ehc000$seamless_loading_screen$attemptToTakeScreenshot exceeds the maximum allowed value: 0. Increase the value of maxShiftBy to suppress this warning.

[Info: 2023-08-25 16:06:09.6188156: MinecraftJavaLoggingContext.cpp(52)] Game/FabricLoader/Mixin (Render thread) Warn @Inject(@At("INVOKE")) Shift.BY=2 on seamless_loading_screen-common.mixins.json:GameRendererMixin from mod seamless_loading_screen::handler$egj000$seamless_loading_screen$attemptToTakeScreenshot exceeds the maximum allowed value: 0. Increase the value of maxShiftBy to suppress this warning.

**Comment by EGOIST1372** [comment]
here is the modlist
txt format 
[mods.txt](https://github.com/Minenash/Seamless-Loading-Screen/files/12468510/mods.txt)

and list format
3dskinlayers-fabric-1.5.4-mc1.20.1.jar
advancementinfo-1.20-fabric0.83.0-1.4.jar
AdvancementPlaques-1.20.1-fabric-1.4.11.jar
AmbientEnvironment-fabric-1.20.1-11.0.0.1.jar
AmbientSounds_FABRIC_v5.2.22_mc1.20.1.jar
animatica-0.6+1.20.jar
antighost-1.20-fabric0.83.0-1.1.5.jar
architectury-9.1.12-fabric.jar
armorchroma-1.2.6.jar
ash_api-fabric-3.0.2+1.20.1.jar
atmosfera-2.0.0+mc1.20.jar
audioplayer-1.20.1-1.7.0.jar
auudio_fabric_1.0.3_MC_1.20.jar
axolotl-item-fix-1.1.7.jar
balm-fabric-1.20-7.0.7.jar
beenfo-1.20-fabric0.83.0-1.3.3-spigot.jar
betterchunkloading-1.20.1-2.1.jar
BetterF3-7.0.1-Fabric-1.20.1.jar
bettermounthud-1.2.2.jar
BetterPingDisplay-Fabric-1.20.1-1.1.1.jar
biomeinfo-1.20-13.jar
blanket-client-tweaks-1.1.4.jar
blur-3.1.0.jar
Boat-Item-View-Fabric-1.20.1-0.0.5.jar
bobby-5.0.1.jar
Bookshelf-Fabric-1.20.1-20.0.3.jar
cakechomps-fabric-6.1.0+1.20.1.jar
camerautils-1.20.1-1.0.5.jar
cave_dust-1.4.1.jar
cem-0.8.0.jar
chatpatches-201.5.5.jar
chat_heads-0.10.20-fabric-1.20.jar
cherishedworlds-fabric-6.1.1+1.20.1.jar
chunksending-1.20.1-2.6.jar
CITResewn-1.1.3+1.20.jar
cleanview-1.20.1-v1-fabric.jar
ClearDespawn-fabric-1.20.1-1.1.13.jar
clickadv-fabric-1.20.1-3.2.jar
clickthrough-1.20-fabric0.83.0-0.4.1.jar
clientcrafting-fabric-1.20.1-1.7.jar
cloth-config-11.0.99-fabric.jar
Clumps-fabric-1.20.1-12.0.0.3.jar
collective-1.20.1-6.65.jar
connectivity-fabric-1.20.1-4.5.jar
continuity-3.0.0-beta.3+1.20.1.jar
Controlling-fabric-1.20.1-12.0.1.jar
CreativeCore_FABRIC_v2.10.28_mc1.20.1.jar
CreativeOnePunch-1.3-universal.jar
CullLessLeaves-1.3.0.jar
cupboard-fabric-1.20.1-1.8.jar
cyclepaintings-1.20.1-3.2.jar
DarkPaintings-Fabric-1.20.1-17.0.2.jar
deathlog-0.3.2+1.20.jar
drippyloadingscreen_fabric_2.2.2_MC_1.20-1.20.1.jar
dynamic-fps-2.4.0.jar
dynview-fabric-1.20.1-3.2.jar
eating-animation-1.9.4+1.20.jar
enhancedblockentities-0.9+1.20.jar
entityculling-fabric-1.6.2-mc1.20.jar
entity_texture_features_fabric_1.20-4.5.1.jar
extra-sounds-2.3.1+1.20.1~lonefelidae16-build.1.jar
fabric-api-0.86.1+1.20.1.jar
fabric-language-kotlin-1.10.8+kotlin.1.9.0.jar
fabricskyboxes-0.7.2+mc1.20.1.jar
fallingleaves-1.15.2+1.20.1.jar
fancymenu_fabric_2.14.7-3_MC_1.20.jar
fastpaintings-1.20-1.1.1-fabric.jar
FastScrolling-1.19.2-fabric-1.0.2.jar
ferritecore-6.0.0-fabric.jar
fm_audio_extension_fabric_1.1.1_MC_1.20.jar
ForgeConfigAPIPort-v8.0.0-1.20.1-Fabric.jar
fpsdisplay-3.1.0+1.20.x.jar
freecam-fabric-1.2.0+1.20.jar
fuelinfo-1.0.4+1.20.jar
gpumemleakfix-fabric-1.20.1-1.7.jar
held-item-info-1.5.0.jar
Highlighter-1.20.1-fabric-1.1.6.jar
horse-stats-vanilla-4.3.0.jar
Iceberg-1.20.1-fabric-1.1.15.jar
ImmediatelyFast-1.2.1+1.20.1.jar
improvedsigns-1.3.1.jar
indium-1.0.25+mc1.20.1.jar
interdimensional-map-markers-1.0.2.jar
InventoryProfilesNext-fabric-1.20-1.10.7.jar
invhud.fabric.1.20-3.4.18.jar
iris-mc1.20.1-1.6.8.jar
isometric-renders-0.4.5+1.20.jar
ItemBorders-1.20.1-fabric-1.2.0.jar
itemswapper-fabric-0.5.3-mc1.20.1.jar
KeepHeadNames-1.5.1-fabric-1.19.3.jar
konkrete_fabric_1.6.1_MC_1.20.jar
krypton-0.2.3.jar
lazydfu-0.1.3.jar
LegendaryTooltips-1.20.1-fabric-1.4.4.jar
libIPN-fabric-1.20-4.0.0.jar
light-overlay-8.0.0.jar
limitedchunks-fabric-1.20.1-3.8.jar
lithium-fabric-mc1.20.1-0.11.2.jar
loadmyresources_fabric_1.0.4-1_MC_1.20.jar
make_bubbles_pop-0.1.1-1.19.4.jar
malilib-fabric-1.20.1-0.16.1.jar
MapTooltip-fabric-1.20-3.0.0.jar
MiniEffects-1.20-fabric-7.0.0.jar
minihud-fabric-1.20.1-0.27.0.jar
mixintrace-1.1.1+1.17.jar
modmenu-7.2.1.jar
moonlight-1.20-2.8.3-fabric.jar
nicephore-fabric-1.19.3-1.0.1.jar
notenoughanimations-fabric-1.6.4-mc1.20.jar
onsoulfire-1.20.1.jar
optigui-2.1.5.jar
owo-lib-0.11.1+1.20.jar
Paintings-fabric-1.20.1-11.0.0.1.jar
peek-1.20.1-1.1.8.jar
persistentinventorysearch-1.20.1-1.0.jar
PresenceFootsteps-1.9.0.jar
Prism-1.20.1-fabric-1.0.5.jar
puzzle-1.5.2+1.20.jar
recursive-resources-2.5.2+1.20.jar
reeses_sodium_options-1.6.5+mc1.20.1-build.95.jar
RoughlyEnoughItems-12.0.645.jar
screenshot-to-clipboard-1.0.9-fabric.jar
seamless-1.4.1-fabric-mc1.20.jar
seamless-loading-screen-2.0.0+1.20.1-fabric.jar
Searchables-fabric-1.20.1-1.0.1.jar
show-me-your-skin-1.6.11+1.20.jar
shulkerboxtooltip-fabric-4.0.4+1.20.1.jar
signtools-fabric.1.20.1-1.0.3.jar
sit-1.20-24.jar
smoothchunk-fabric-1.20.1-3.1.jar
sodium-extra-0.5.1+mc1.20.1-build.112.jar
sodium-fabric-mc1.20.1-0.5.2.jar
sodium-shadowy-path-blocks-3.2.0.jar
soundphysics-fabric-1.20.1-1.2.1.jar
starlight-1.1.2+fabric.dbc156f.jar
status-1.20.1-1.0.4.jar
status-effect-bars-1.0.3.jar
stendhal-1.3.9-1.20.jar
toomanybinds-0.3.3.jar
transparent-fabric-8.0.1+1.20.1.jar
voicechat-fabric-1.20.1-2.4.24.jar
WI-Zoom-1.4-MC1.20.1.jar
yet-another-config-lib-fabric-3.0.3+1.20.jar

i will record a video soon but first i need to know how to clear the cache of the mod so it wont stuck at screenshot

**Comment by Dragon-Seeker** [comment]
Hmm, it seems sodium mixin config on our end isn't working which might be leading to the issue ngl. I'll see about updating such since that is kinda of important.

**Comment by Dragon-Seeker** [comment]
Could you try the latest release to confirm if this is still a issue: https://modrinth.com/mod/seamless-loading-screen/versions

**Comment by EGOIST1372** [comment]
finally
it fixed both issues
and one other thing that i wanted to create as issue but i was waiting for this 2 to fix also got fixed xD
and thaat was the issue when percentage start to fill up it didnt show the screenshot overlay under it, it was just dirt and after it reached to 100% it would show screenshot for a split sec then load into world
but with this release all 3 issues are fixed
Thank you so much <3 <3 <3
you can close this issue

**Comment by Dragon-Seeker** [comment]
Cool, glad it worked.
