### ISSUE TITLE
[Bug] Origins buttons do not work if rejoining a world with the same name.

### ISSUE THREAD

**Issue by SlayerTheChikken** [Minenash/Seamless-Loading-Screen#83]
MC 1.19.2, Fabric, mod version 2.0.1

How to trigger bug (easily:)
Create a new world with default everything, save and exit, delete the world you just made, make a new world with default everything, origins menu non functional. 

Seamless loading screen disables input until it detects the world as loaded, for new worlds this issue does not occur because seamless loading screen is not being used, however by deleting the "New World" and creating a new one (with the same exact name) the mod shows the last screenshot and when the world creation is done the buttons for origins are unclickable.

You can change "disableCamera" to false to prevent input from being disabled, this breaks other things however when you leave the game again (probably because it thinks the world never loaded,) for example fancy menu (see below.)

![image](https://github.com/Minenash/Seamless-Loading-Screen/assets/20819543/b4f5cd3c-cd92-44a4-b794-04ca20a5cdf1)

**Comment by Dragon-Seeker** [comment]
Okay, so I added another failsafe to prevent lockups like this by resetting the needed values if someone else opens a screen right after DownloadingTerrainScreen is replaced. Will see about getting such in the next update.

**Comment by Dragon-Seeker** [comment]
The following [github action](https://github.com/Minenash/Seamless-Loading-Screen/actions/runs/6032433081) once finished should contain the fix which will get published within the future.

**Comment by SlayerTheChikken** [comment]
Thank you <3

**Comment by Dragon-Seeker** [comment]
Such fix has been released on modrinth and curseforge, marking this as resolved

**Comment by SlayerTheChikken** [comment]
This fixed the issue thank you!
