### ISSUE TITLE
[Bug] Changing Dimensions Triggers Screenshot to appear quickly on Screen

### ISSUE THREAD

**Issue by Jim3535** [Minenash/Seamless-Loading-Screen#84]
When going through nether portals either way, the saved screenshot is show for a second after the portal effect, but before the game loads the new dimension. This has a rather disorienting effect. 

Minecraft 1.20.1
Fabric loader 0.14.22

Mods:
* seamless-loading-screen-2.0.1+1.20.1-fabric
* cloth-config-11.1.106-fabric
* fabric-api-0.87.0+1.20.1
* modmenu-7.2.1

**Comment by Dragon-Seeker** [comment]
Can confirm this exists and found to happen also when entering the End Dimension

**Comment by Dragon-Seeker** [comment]
Should be fixed in ef248b3d5fffef622f2f57d77ecbdafd0ab7e136 as I now check if fade mode is active or not before replacing screen. You can confirm in the [action](https://github.com/Minenash/Seamless-Loading-Screen/actions/runs/6077289558).

**Comment by EmmaKnijn** [comment]
This is still here on v2.0.1 1.20.1

**Comment by Dragon-Seeker** [comment]
> This is still here on v2.0.1 1.20.1

Yeah it was fixed in 2.0.2
