### ISSUE TITLE
[Bug] Forge - 1.19.2 Doesn't create screenshots

### ISSUE THREAD

**Issue by DTech10** [Minenash/Seamless-Loading-Screen#88]
Rubidium: mixin.features.gui.fast_loading_screen=false

No Crashes, the mod did create the folders inside the screenshot folder except for the world screenshot itself

[Latest Logs](https://mclo.gs/sI3BIaR)

**Comment by mikkolukas** [comment]
Same issue, but no other mods installed.

File installed: seamless-loading-screen-2.0.2+1.19.2-forge.jar
Minecraft version: 1.19.2
Forge version: 43.2.23

Other mods installed: No

The mod doesn't do anything.

[Logs](https://paste.ee/p/UwKsu)

**Comment by mikkolukas** [comment]
I had a hunch that maybe the Forge version used was at play here. @DTech10 also used 43.2.23.

Narrowing in, I have tested the following versions:

* 43.2.0: Works
* 43.2.10: Works
* 43.2.19: Works
* 43.2.20: Doesn't work
* 43.2.23: Doesn't work

I hope this helps 🙂

**Comment by DTech10** [comment]
thx 👍

**Comment by Dragon-Seeker** [comment]
> I had a hunch that maybe the Forge version used was at play here. @DTech10 also used 43.2.23.
> 
> Narrowing in, I have tested the following versions:
> 
>     * 43.2.0: Works
> 
>     * 43.2.10: Works
> 
>     * 43.2.19: Works
> 
>     * 43.2.20: Doesn't work
> 
>     * 43.2.23: Doesn't work
> 
> 
> I hope this helps 🙂

Uhhh so 43.2.20 sates changes of: `Re-add in-game mod menu (#9655)` which is quite odd such breaks Seamless but thank you as I now have a lead to investigate off of.

**Comment by Dragon-Seeker** [comment]
NVM forge patch completely screwed my mixin for taking the Screen shot meaning such would only happen when using the Ingame Forge Modmenu... ARGGGG

**Comment by Dragon-Seeker** [comment]
Such should be fixed with the various latest [Actions](https://github.com/Minenash/Seamless-Loading-Screen/actions/runs/6189942060). Seem to work in dev so I hope it works in prod.

**Comment by Dragon-Seeker** [comment]
Update to fix such a issue has been released

**Comment by DTech10** [comment]
it works👍, do i still need the "mixin.features.gui.fast_loading_screen=false" line in rubidium-mixins?

ok nvm, it still needed
this can be closed now
holy crap it even works with Panorama Screens
