### ISSUE TITLE
[BUG] Incompatibility with Bedrockify

### ISSUE THREAD

**Issue by SylisMC** [Minenash/Seamless-Loading-Screen#9]
Incompatibility with [Bedrockify](https://www.curseforge.com/minecraft/mc-mods/bedrockify)
I've made a post on [bedrockify here](https://github.com/juancarloscp52/BedrockIfy/issues/45), I'm not sure if you two are able to work together to fix this? but heres what the issue looks like
![error](https://user-images.githubusercontent.com/19602662/104078023-04396700-51ea-11eb-959e-d88263bd23d3.gif)

**Comment by Minenash** [comment]
Hmm, this'll be interesting, because they're replacing the screen then I'm editing. Tomorrow I'll try to see if I can get the screenshot to load on their screen instead of the panama.

**Comment by SylisMC** [comment]
The owner of bedrockify is looking into this aswall, you two may be able to work together on this one @juancarloscp52

**Comment by Minenash** [comment]
As soon as the small fix is done on his side and is released, I'll release a version with the mod compat mixin.

**Comment by Minenash** [comment]
Since the bug is fixed on their side, the compat is added on mine. I still want to fix a bug or two before doing a full release (not related to Bedrockify), but here's a beta release with Bedrockify's compat:
https://github.com/Minenash/Seamless-Loading-Screen/releases/tag/v1.1.1-beta.1%2B1.16
