### ISSUE TITLE
[Bug] Crash on exiting world when resolution is set to "Native"

### ISSUE THREAD

**Issue by spacky1** [Minenash/Seamless-Loading-Screen#92]
[latest.log](https://github.com/Minenash/Seamless-Loading-Screen/files/12898430/latest.log)

**Comment by Dragon-Seeker** [comment]
Hmmm such a bug was not caught for a long time, this is caused by setting the Frame Buffer of the given window to 0 width and height. Ill see about getting such fixed coming up

**Comment by Aces-and-Jacks** [comment]
Can you also apply this fix to 1.19.2?

**Comment by Dragon-Seeker** [comment]
> Can you also apply this fix to 1.19.2?

Possibly

**Comment by Dragon-Seeker** [comment]
This is fixed in later versions and a backport is not going to happen due to not having time for such
