### ISSUE TITLE
Config not populating or saving

### ISSUE THREAD

**Issue by LessThanBenji** [Minenash/Seamless-Loading-Screen#94]
Hi, I'm using 2.1.0 on 1.20.2 with Fabric, and I've noticed none of the changes I make to the config in-game are being saved or respected. Every time I return to the config options after saving and exiting, they've all reset to their defaults. I then went to .\config\seamless_loading_screen.json and noticed the file is empty except for a pair of curly brackets "{}". The log shows the config file is being recognized and deserialized upon each load, but it seems to have never populated with anything from the first initialization.

Will provide logs and/or screenshots if asked, but for me at least this seems to happen irrespective of other mods being present or not and therefore seems quite easy to reproduce.

Regardless, the default settings make a lot of sense and at the end of the day make for an awesome mod to use, thank you!

**Comment by Dragon-Seeker** [comment]
Can confirm such is an issue, seems to be caused due to the change over to V2 Yacl config without fully testing the conversion. Deprecated Annotations for config entries were left leading to no values being saved, will try to get a fix out soon for such.

**Comment by LessThanBenji** [comment]
Much appreciated. Thank you for your awesome work!

**Comment by Dragon-Seeker** [comment]
Should be fixed in latest release for 1.20.2

**Comment by LessThanBenji** [comment]
Works like a charm. Thank you!
